name: Django CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build with docker-compose
      run: docker-compose up -d
    - name: Check docker-compose version
      run: docker-compose version
    - name: Run Tests
      run: docker-compose exec -T django sh -c 'python ./manage.py test'
